DROP TABLE IF EXISTS boards CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
ALTER TABLE IF EXISTS ONLY public.boards DROP CONSTRAINT IF EXISTS pk_board_id CASCADE;
ALTER TABLE IF EXISTS ONLY public.cards DROP CONSTRAINT IF EXISTS pk_card_id CASCADE;



CREATE TABLE boards (
    id       SERIAL PRIMARY KEY NOT NULL,
    board_title VARCHAR(50) NOT NULL
);


CREATE TABLE cards (
    id   SERIAL PRIMARY KEY NOT NULL,
    board_id INTEGER NOT NULL,
    title VARCHAR(15) NOT NULL,
    status VARCHAR(15) NOT NULL
);


ALTER TABLE ONLY cards
    ADD CONSTRAINT fk_board_id FOREIGN KEY (board_id) REFERENCES boards(id);

